### ISSUE TITLE
Deadlock when stopping daemon while syncing

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#74] opened 2018-02-08 21:54 UTC
When a syncing daemon with block creator module is stopped using the SIGINT signal (ctrl+c) while its syncing, it enters a deadlock.

**Comment by LeeSmet** [comment] 2018-02-08 22:05
Also occurs without the blockcreator module

**Comment by LeeSmet** [comment] 2018-02-22 14:11
```
goroutine 1 lock 0xc4201e0d58
~/go/src/github.com/rivine/rivine/sync/threadgroup.go:127 sync.(*ThreadGroup).Stop { tg.bmu.Lock() } <<<<<
~/go/src/github.com/rivine/rivine/modules/consensus/consensusset.go:253 consensus.(*ConsensusSet).Close { return cs.tg.Stop() }
~/go/src/github.com/rivine/rivine/rivined/daemon.go:211 rivined.startDaemon.func3 { err := cs.Close() }
~/go/src/github.com/rivine/rivine/rivined/daemon.go:318 rivined.startDaemon { return nil }
~/go/src/github.com/rivine/rivine/rivined/commands.go:40 rivined.startDaemonCmd { err := startDaemon(globalConfig) }
~/go/src/github.com/rivine/rivine/vendor/github.com/spf13/cobra/command.go:575 cobra.(*Command).execute { c.Run(c, argWoFlags) }
~/go/src/github.com/rivine/rivine/vendor/github.com/spf13/cobra/command.go:661 cobra.(*Command).ExecuteC { err = cmd.execute(flags) }
~/go/src/github.com/rivine/rivine/vendor/github.com/spf13/cobra/command.go:620 cobra.(*Command).Execute { _, err := c.ExecuteC() }
~/go/src/github.com/rivine/rivine/rivined/commands.go:149 rivined.SetupDefaultDaemon { if err := root.Execute(); err != nil { }
~/go/src/github.com/rivine/rivine/cmd/rivined/main.go:10 main.main { rivined.SetupDefaultDaemon(cfg) }
/usr/lib/go/src/runtime/proc.go:198 runtime.main { fn() }

goroutine 127 lock 0xc4201e0d58
~/go/src/github.com/rivine/rivine/sync/threadgroup.go:55 sync.(*ThreadGroup).Add { tg.bmu.Lock() } <<<<<
~/go/src/github.com/rivine/rivine/modules/consensus/consensusset.go:296 consensus.(*ConsensusSet).Height { err := cs.tg.Add() }
~/go/src/github.com/rivine/rivine/modules/consensus/block_validation.go:66 consensus.checkTarget { stakemodifier := cs.CalculateStakeModifier(cs.Height() + 1) }
~/go/src/github.com/rivine/rivine/modules/consensus/block_validation.go:114 consensus.stdBlockValidator.ValidateBlock { if !checkTarget(b, target, valueofblockstakeoutput, bv.cs) { }
<autogenerated>:1 consensus.(*stdBlockValidator).ValidateBlock ???
~/go/src/github.com/rivine/rivine/modules/consensus/accept.go:62 consensus.(*ConsensusSet).validateHeaderAndBlock { return cs.blockValidator.ValidateBlock(b, minTimestamp, parent.ChildTarget, parent.Height+1) }
~/go/src/github.com/rivine/rivine/modules/consensus/accept.go:211 consensus.(*ConsensusSet).managedAcceptBlock.func1 { err := cs.validateHeaderAndBlock(boltTxWrapper{tx}, b) }
~/go/src/github.com/rivine/rivine/vendor/github.com/coreos/bbolt/db.go:626 bbolt.(*DB).View { err = fn(t) }
~/go/src/github.com/rivine/rivine/modules/consensus/accept.go:203 consensus.(*ConsensusSet).managedAcceptBlock { err := cs.db.View(func(tx *bolt.Tx) error { }
~/go/src/github.com/rivine/rivine/modules/consensus/synchronize.go:220 consensus.(*ConsensusSet).managedReceiveBlocks { acceptErr := cs.managedAcceptBlock(block) }
~/go/src/github.com/rivine/rivine/modules/consensus/synchronize.go:246 consensus.(*ConsensusSet).threadedReceiveBlocks { return cs.managedReceiveBlocks(conn) }
~/go/src/github.com/rivine/rivine/modules/consensus/consensusset.go:181 consensus.threadedReceiveBlocks)-fm { gateway.RegisterConnectCall("SendBlocks", cs.threadedReceiveBlocks) }
~/go/src/github.com/rivine/rivine/modules/gateway/rpc.go:57 gateway.(*Gateway).managedRPC { return fn(conn) }
~/go/src/github.com/rivine/rivine/modules/gateway/peers.go:455 gateway.(*Gateway).managedConnect.func1 { err := g.managedRPC(addr, name, fn) }
```

Problem here is that while we are syncing, every block is validated, which locks the thread group. But the thread group is already locked because it is stopping.

**Comment by lafont-e** [comment] 2018-02-27 12:45
I've reviewed some of the code, and there are things that I don't like in the ThreadGroup code, or 

* **Why using a channel as a flag to stop the ThreadGroup ?** As I see from the code, is a channel that is used once, so his work can be rightly done by a boolean, this will add persistent to the stopped state, which currently there are none

* **isStopped function, stops to work, after the 1st call** as we are using a channel, the channel is consumed after we call isStopped(), any subsequent calls to it will return false
```go
func (tg *ThreadGroup) isStopped() bool {
	tg.once.Do(tg.init)
	select {
	case <-tg.stopChan:
		tg.stopChan <- struct{} // Re-entry of the stopChannel, this makes isStopped persistent
                                                    // Only works if stopChan is operated from inside ThreadGroup
		return true
	default:
		return false
	}
}
```

There are another thing I just don't really understand about stopChan, as its read from other modules, and if the mission is to stop ThreadGroup, as soon as "peer.go:110"  reads it , then it will not stop ThreadGroup from working, as the channel will be consumed and isStopped will return false.

**Comment by lafont-e** [comment] 2018-02-27 13:11
> Problem here is that while we are syncing, every block is validated, which locks the thread group. But the thread group is already locked because it is stopping.
Not sure this is what causes the issue, as the lock (no matter who asked for it first) should prevent the other code from executing.

**Comment by lafont-e** [comment] 2018-02-27 13:19
I see that the stopGroup channel is used outside ThreadGroup, "gateway/peers.go:110" that means that the channel data is consumed, and subsequent calls to "isStopped" are going to return false, until the channel is closed, from that moment it will return true. Not sure if this is the intended behaviour

**Comment by LeeSmet** [comment] 2018-03-01 10:01
>I see that the stopGroup channel is used outside ThreadGroup, "gateway/peers.go:110" that means that the channel data is consumed, and subsequent calls to "isStopped" are going to return false, until the channel is closed, from that moment it will return true. Not sure if this is the intended behaviour

Channel data can't be consumed since nothing is ever written on it. These methods will continue to return true after the Tg is stopped. I suggest reviewing the go docs for the behavior of (closed) channels , and selects with blocking functions to get a better idea about what is happening

**Comment by GlenDC** [comment] 2018-03-01 13:11
Fairly sure the entire thread group implementation is pretty flawed as it is. Not sure if we want to keep it. But if we do, I don't think it makes sense to protect the `Add` function (together with some others) behind a mutex, while `Done` is not protected at all, as that could lead to a negative-counter panic due to a delayed `Add`.

Then again, the proposed solution of @lafont-e in PR #107 is not the right threadgroup-keep approach either.

**Comment by GlenDC** [comment] 2018-03-01 13:37
I think the goal and motivation behind Threadgroup is sufficient enough that we probably do want to keep it, but its implementation raises question marks imno.

**Comment by LeeSmet** [comment] 2018-03-01 14:10
disregarding the discussion of whether the design and / or implementation of the threadgroup is up to standard, it just feels wrong to change the synchronization structure because 1 thing is giving syncing issues even if the other work fine. Just my opinion.

P.S.: as seen in the PR, changing the logic in the threadgroup can easily open up new bugs in the form of race conditions, so care should be taken if we do move in that direction

**Comment by GlenDC** [comment] 2018-03-01 14:16
You are right, if we'll make a drastic change to that sync code, we'll have to be very carefully and sure for sure, especially as our testing is still of very poor quality. So it's going to be very hard to avoid bugs. But perhaps that's unavoidable given the current state. Even so, we're still prior to production, so if there is any time to do so, it is definitely now, rather than in a couple of months.

**Comment by lafont-e** [comment] 2018-03-01 16:18
I've added some code to threadgroup.go so I can know when a lock is asked, when it's released, who asked for it and what threadgroup is processing it

The test is done on an unsynced rivined so as soon as the connections are made, the daemon starts to ask for blocks so he can reach the full blockchain

Once the daemon is up and syncinc then I send the SIGINT signal to the process and the daemon starts to shutdown

```
Caught stop signal, quitting...
Closing block creator...
			Stop: (0xc420302778) caller modules/blockcreator/blockcreator.go#137	...locked...			
				Stop mu1: (0xc420302778) caller modules/blockcreator/blockcreator.go#137	...locked mu1...			
			Add: (0xc4202b61d0) caller modules/consensus/subscribe.go#175	...locked...Unlocked
		                                                                                                 ...unlocked mu1
				Stop mu2: (0xc420302778) caller modules/blockcreator/blockcreator.go#137	...locked mu2......unlocked mu2
			                                                                                      	Unlocked
			Add: (0xc4202b61d0) caller modules/consensus/subscribe.go#175	...locked...Unlocked
			Add: (0xc4202b61d0) caller modules/consensus/consensusset.go#296	...locked...Unlocked
			Add: (0xc4202b61d0) caller modules/consensus/consensusset.go#296	...locked...Unlocked
			Add: (0xc4202860e8) caller modules/gateway/peers.go#118	...locked...Unlocked
			Add: (0xc4202b61d0) caller modules/consensus/consensusset.go#296	...locked...Unlocked
Closing wallet...
			Stop: (0xc4203061c0) caller modules/wallet/wallet.go#148	...locked...			
				Stop mu1: (0xc4203061c0) caller modules/wallet/wallet.go#148	...locked mu1......unlocked mu1
				Stop mu2: (0xc4203061c0) caller modules/wallet/wallet.go#148	...locked mu2......unlocked mu2
																					Unlocked
			Add: (0xc4202b61d0) caller modules/consensus/subscribe.go#175		...locked...Unlocked
			Add: (0xc4202b61d0) caller modules/consensus/consensusset.go#296	...locked...Unlocked
			Add: (0xc4202b61d0) caller modules/consensus/consensusset.go#296	...locked...Unlocked
			Add: (0xc4202b61d0) caller modules/consensus/consensusset.go#296	...locked...Unlocked
Closing transaction pool...
			Add: (0xc4202b61d0) caller modules/consensus/subscribe.go#175	...locked...Unlocked
Closing consensus set...
			Stop: (0xc4202b61d0) caller modules/consensus/consensusset.go#253	...locked...			
				Stop mu1: (0xc4202b61d0) caller modules/consensus/consensusset.go#253	...locked mu1......unlocked mu1
			Add: (0xc4202b61d0) caller modules/consensus/consensusset.go#296				
			Add: (0xc4202860e8) caller modules/gateway/peers.go#118	...locked...Unlocked
			Add: (0xc4202860e8) caller modules/gateway/peers.go#118	...locked...Unlocked
			Add: (0xc4202860e8) caller modules/gateway/rpc.go#188	...locked...Unlocked
```

From the last lines we can see that consensusset.go#253 aquires a lock, it advances until the mu lock is released, and the next  instruction in the code is "tg.wg.Wait()" the next line consensusset.go#296, tries to adquire the bmu lock again in the Add method but is already locked by the previous call to Stop. 

The program does not stop as module/gateway is already working and consensus is locked.

The solution is to refactor Stop, so this race condition does not appear, or advance the isStopped check, or change the closing order so gateway is stopped (this will generate a panic, but at least will stop) , or any other option I don't know enough the code to be able to make a proposition.

From my understanding of the code (rather limited) advancing the check is the safe one to do. Or refactor ThreadGroup and risk adding other bugs, dead locks, etc ....

**Comment by lafont-e** [comment] 2018-03-01 16:21
If this channel is not sending/receiving tokens, then as I see it we are using the channel just to do the work of a boolean. 

Maybe there can be other reasons to use a channel, but I'm not aware of which ones could they be

**Comment by LeeSmet** [comment] 2018-03-02 08:53
A bool would require a lock, whereas an unbuffered channel with select statements doesn't. There is some info about this in the official go doc (about channels in general as well as select statements and their behavior with (un)buffered channels), I suggest reading up on that

**Comment by LeeSmet** [comment] 2018-06-06 15:20
After fixing this, #384 was introduced, though I will track it in a separate issue since I don't really see how this can be related

**Closed** 2018-06-07 14:07 UTC
Labels: priority_major, type_bug
