### ISSUE TITLE
Arbitrary data example from an external program

### ISSUE THREAD

**Issue by nvinken** [rivine/rivine#33] opened 2017-03-01 15:54 UTC
Add some api calls to make it easy to use the arbitrary data in a transaction. The maximum size will be probably set to 1kB. 
Maybe we need to have some type definitions so we can allready have some metadata of the data in the blob.
The minimum fee allowed on a transaction will depend on the size of that transaction and thus depend a lot on the size of this arbitrary data.

**Comment by robvanmieghem** [comment] 2017-05-22 09:49
Duplicate of https://github.com/rivine/rivine/issues/29

**Closed by robvanmieghem** 2017-05-22 09:49 UTC
Labels: process_duplicate, type_feature, wontfix
